services:
    redis:
        image: redis/redis-stack
        ports:
          - "16379:6379"
        volumes:
          - $PWD/data:/data
    app:
        restart: always
        build: .
        ports:
            - "8080:80"
        volumes:
            - $PWD:/app
        depends_on:
            - redis
        command: /start-reload.sh

    test:
        build:
            context: .
            dockerfile: Dockerfile.test
        depends_on:
            - redis
        volumes:
            - $PWD:/app
        entrypoint: "pytest -s"

    worker:
        build:
            context: .
            dockerfile: Dockerfile.worker
        depends_on:
            - redis
